projects:
  lambieApi:
    schemaPath: amplify/backend/api/lambieApi/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/services/people/people-api.ts
        docsFilePath: src/services/people/graphql
extensions:
  amplify:
    version: 3
